/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel;
import java.util.*;
import com.sun.org.apache.bcel.internal.generic.Select;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.*;
//import java.text.ParseException;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class CheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        initComponents();
    }
    SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
    Calendar call = Calendar.getInstance();
    int ranNum = ThreadLocalRandom.current().nextInt(100,999);
    Connection con;
    ResultSet rs;
    PreparedStatement pst;
    Statement st;
    String bed;
    String roomtype;
    String roomnumber;
    String view;
    String price;
    private void room(){
        number.removeAllItems();
        price1.setText("");
        bed=(String)bed1.getSelectedItem();
        roomtype=(String)type.getSelectedItem();
        view = (String)views.getSelectedItem();
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_manager","root","123");
            String sql = "select * from room where Bed='"+bed+"' and View ='"+view+"' and RoomType='"+roomtype+"' and Status='Not Booked'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                number.addItem(rs.getString(1));
        Calendar call = Calendar.getInstance();
        SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date dateBefore = jDateChooser1.getDate();
        java.util.Date dateAfter = jDateChooser2.getDate();
        long difference = Math.abs(dateAfter.getTime() - dateBefore.getTime());
        int noOfDayStay = (int) difference /(1000*60*60*24);
        if(noOfDayStay == 0) noOfDayStay=1;
             int money = Integer.valueOf(rs.getString(5)) * noOfDayStay;
             price1.setText(String.valueOf(money)); 
            }    
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    int ID =0;
     private void CountDep(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_manager","root","123");
            st = con.createStatement();
            rs = st.executeQuery("select Max(ID) from checkin");
            rs.next();
            ID = rs.getInt(1)+1;
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(CheckIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
     private void login(){
         try{
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_manager","root","123");
             String sql = "insert into login values(?,?)";
             pst =con.prepareStatement(sql);
             pst.setString(1, (String) number.getSelectedItem());
             pst.setInt(2, ranNum);
             int add = pst.executeUpdate();
         }catch(Exception e){
             e.printStackTrace();
         }
     }  private void status(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_manager","root","123");
            String sql = "Update room set Status = 'Booked' where RoomNumber = ?";
            pst = con.prepareStatement(sql);
            pst.setString(1,(String)number.getSelectedItem());
            int row = pst.executeUpdate();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
     }
     private void clear(){
         name.setText("");
         phone.setText("");
         nat.setSelectedItem("1");
         children.setSelectedItem(1);
         email.setText("");
         card.setText("");
         add.setText("");
         bed1.setSelectedItem(1);
         type.setSelectedItem(1);
         views.setSelectedItem(1);
         number.setSelectedItem(null);
         price1.setText("");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        children = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        card = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bed1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        views = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        number = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        nat = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        gender1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        adult = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1266, 555));
        setMinimumSize(new java.awt.Dimension(1266, 555));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Adobe Arabic", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Customer Registration & Check IN.png"))); // NOI18N
        jLabel1.setText("Customer Check IN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Full Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 280, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 280, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 280, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 280, -1));

        phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, -1));

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 280, -1));

        children.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        children.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        children.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childrenActionPerformed(evt);
            }
        });
        getContentPane().add(children, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 60, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ID Card");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 290, -1));

        card.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 290, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 290, -1));

        add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 290, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Children(0-17 years old)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Bed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 290, -1));

        bed1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bed1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A single bed", "Two single bed", "A double bed", "King size bed", "Extra Bed" }));
        bed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bed1ActionPerformed(evt);
            }
        });
        getContentPane().add(bed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 290, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 290, -1));

        type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "VIP" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 290, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("View");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 290, -1));

        views.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        views.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beach", "City", "Normal" }));
        views.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsActionPerformed(evt);
            }
        });
        getContentPane().add(views, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 290, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Room Number");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 290, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Price");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 290, -1));

        price1.setEditable(false);
        price1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 290, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 253, 153));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 516, 181, 38));

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 255, 153));
        jButton3.setText("Room Alloation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 180, 50));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 57, -1, -1));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 11, -1, -1));

        number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 290, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, -1, -1));

        nat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan  ", "Albania  ", "Algeria  ", "Andorra  ", "Angola  ", "Antarctica  ", "Antigua and Barbuda  ", "Argentina  ", "Armenia  ", "Aruba  ", "Australia  ", "Austria  ", "Azerbaijan  ", "Bahamas  ", "Bahrain  ", "Bangladesh  ", "Barbados  ", "Belarus  ", "Belgium  ", "Belize  ", "Benin  ", "Bhutan  ", "Bolivia  ", "Bosnia and Herzegovina  ", "Botswana  ", "Brazil  ", "Brunei  ", "Bulgaria  ", "Burkina Faso  ", "Burundi  ", "Cambodia  ", "Cameroon  ", "Canada  ", "Canary Islands  ", "Cape Verde Islands  ", "Cayman islands  ", "Central African Republic  ", "Chad  ", "Chile  ", "China  ", "Colombia  ", "Comoros  ", "Congo  ", "Cook Islands  ", "Costa Rica  ", "Croatia  ", "Cuba  ", "Cyprus  ", "Czech Republic  ", "Democratic Republic of the Congo (Zaire)  ", "Denmark  ", "Djibouti  ", "Dominica  ", "Dominican Republic  ", "East Timor  ", "Ecuador  ", "Egypt  ", "El Salvador  ", "Equatorial Guinea  ", "Eritrea  ", "Estonia  ", "Ethiopia  ", "Federated States of Micronesia  ", "Fiji  ", "Finland  ", "France  ", "French Guyana  ", "French Polynesia  ", "Gabon  ", "Gambia  ", "Georgia  ", "Germany  ", "Ghana  ", "Greece  ", "Greenland  ", "Grenada  ", "Guatemala  ", "Guinea  ", "Guinea Bissau  ", "Guyana  ", "Haiti  ", "Honduras  ", "Hong Kong  ", "Hungary  ", "Iceland  ", "India  ", "Indonesia  ", "Iran  ", "Iraq  ", "Israel  ", "Italy  ", "Ivory Coast/Côte d’Ivoire  ", "Jamaica  ", "Japan  ", "Jordan  ", "Kazakhstan  ", "Kenya  ", "Kiribati  ", "Kosovo  ", "Kuwait  ", "Kyrgyzstan  ", "Laos  ", "Latvia  ", "Lebanon  ", "Lesotho  ", "Liberia  ", "Libya  ", "Liechtenstein  ", "Lithuania  ", "Luxembourg  ", "Macedonia  ", "Madagascar  ", "Malawi  ", "Malaysia  ", "Maldives  ", "Mali  ", "Malta  ", "Marshall Islands  ", "Martinique  ", "Mauritania  ", "Mauritius  ", "Mexico  ", "Moldova  ", "Monaco  ", "Mongolia  ", "Montenegro  ", "Morocco  ", "Mozambique  ", "Myanmar (Burma)  ", "Namibia  ", "Nauru  ", "Nepal  ", "New Caledonia  ", "New Zealand  ", "Nicaragua  ", "Niger  ", "Nigeria  ", "North Korea  ", "Norway  ", "Oman  ", "Pakistan  ", "Palau  ", "Palestine  ", "Panama  ", "Papua New Guinea  ", "Paraguay  ", "Peru  ", "Philippines  ", "Pitcairn Islands  ", "Poland  ", "Portugal  ", "Puerto Rico  ", "Qatar  ", "Republic of Ireland  ", "Republic of San Marino  ", "Romania  ", "Russia  ", "Rwanda  ", "Samoa  ", "Sao Tome  ", "Saudi Arabia  ", "Scotland  ", "Senegal  ", "Serbia  ", "Seychelles  ", "Sierra Leone  ", "Singapore  ", "Slovakia  ", "Slovenia  ", "Solomon Islands  ", "Somalia  ", "South Africa  ", "South Korea  ", "Spain  ", "Sri Lanka  ", "St. Kitts and Nevis  ", "St. Lucia  ", "St. Vincent and The Grenadines  ", "Sudan  ", "Suriname  ", "Swaziland  ", "Sweden  ", "Switzerland  ", "Syria  ", "Taiwan  ", "Tajikistan  ", "Tanzania  ", "Thailand  ", "The Netherlands  ", "The Vatican  ", "Togo  ", "Tonga  ", "Trinidad and Tobago  ", "Tunisia  ", "Turkey  ", "Turkmenistan  ", "Tuvalu  ", "Uganda  ", "Ukraine  ", "United Arab Emirates  ", "United Kingdom  ", "United States  ", "Uruguay  ", "Uzbekistan  ", "Vanuatu  ", "Venezuela  ", "Vietnam  ", "Wales  ", "West Bank and Gaza  ", "Western Sahara  ", "Yemen  ", "Zambia  ", "Zimbabwe  " }));
        getContentPane().add(nat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 280, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Check IN Date ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 290, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Check Out Date");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 290, -1));

        gender1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender1ActionPerformed(evt);
            }
        });
        getContentPane().add(gender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Adult");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 40, -1));

        adult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        adult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultActionPerformed(evt);
            }
        });
        getContentPane().add(adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 60, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 290, 40));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 290, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void childrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childrenActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String mail  = email.getText();
        java.util.Date dateBefore = jDateChooser1.getDate();
        String date = myformat.format(dateBefore);
        java.util.Date dateAfter = jDateChooser2.getDate();
        String date2 = myformat.format(dateAfter);
        if(name.getText().equals("") && phone.getText().equals("") && email.getText().equals("") && card.getText().equals("") && card.getText().equals("")){
            JOptionPane.showConfirmDialog(null, "Please enter full");}
        while(true){
             Pattern p = Pattern.compile("^[a-zA-Z][a-zA-Z0-9]+@[a-zA-Z]+(\\.[a-zA-Z]+){1,3}$");
             if(p.matcher(mail).find() == false ){
               JOptionPane.showConfirmDialog(null, "Email is correct");
               break;
             }else {try{
            CountDep();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_manager","root","123");
            String sql ="insert into `checkin` values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = con.prepareStatement(sql);
            pst.setInt(1, ID);
            pst.setString(2, name.getText());
            pst.setString(3, (phone.getText()));
            pst.setString(4,(String)nat.getSelectedItem());
            pst.setString(5,(String)gender1.getSelectedItem());
            pst.setString(6,email.getText());
            pst.setInt(7, Integer.valueOf(card.getText()));
            pst.setString(8,add.getText());
            pst.setString(9, date);
            pst.setString(10,date2);
            pst.setString(11,(String)(children.getSelectedItem()));
            pst.setString(12,(String)(adult.getSelectedItem()));
            pst.setString(13,(String)(bed1.getSelectedItem()));
            pst.setString(14,(String)(type.getSelectedItem()));
            pst.setString(15,(String)(views.getSelectedItem()));
            pst.setString(16,(String)(number.getSelectedItem()));
            pst.setInt(17, Integer.valueOf(price1.getText()));
            int row = pst.executeUpdate();
            JOptionPane.showConfirmDialog(rootPane, "You have successfully registered the room");
            JOptionPane.showConfirmDialog(null, "Room:"+number.getSelectedItem()+" and Pass: "+ranNum, "Account", JOptionPane.DEFAULT_OPTION);
                  login();
                  status();
                  clear();
                  new Login().setVisible(true);
                  this.dispose();
            con.close();
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this, ex);}   
              break;}}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bed1ActionPerformed
      room();
      String room = (String)number.getSelectedItem();
      if(number.getSelectedItem() == null){
          number.addItem("No Room");
      }
      
    }//GEN-LAST:event_bed1ActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        room();
         String room = (String)number.getSelectedItem();
      if(number.getSelectedItem() == null){
          number.addItem("No Room");
      }
    }//GEN-LAST:event_typeActionPerformed

    private void viewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsActionPerformed
        room();
         String room = (String)number.getSelectedItem();
      if(number.getSelectedItem() == null){
          number.addItem("No Room");
      }
    }//GEN-LAST:event_viewsActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void gender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender1ActionPerformed

    private void adultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adultActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clear();  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JComboBox<String> adult;
    private javax.swing.JComboBox<String> bed1;
    private javax.swing.JTextField card;
    private javax.swing.JComboBox<String> children;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> nat;
    private javax.swing.JComboBox<String> number;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField price1;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JComboBox<String> views;
    // End of variables declaration//GEN-END:variables
}
