/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class OrderFood extends javax.swing.JFrame {
DefaultTableModel tblModel;
    /**
     * Creates new form OrderFood
     */
    public OrderFood() {
        initComponents();
        loadData();
        loaddata();
    }
    Connection con = null;
    ResultSet rs = null,rs1;
    Statement st = null,st1;
    PreparedStatement pst;
    private void loaddata(){
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_manager","root","123");
        String sql ="SELECT * FROM `orderfood`";
        PreparedStatement pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        tblModel.setRowCount(0);
        while(rs.next()){
            String [] row = new String[]{
                rs.getString("ID"), rs.getString("Room"),rs.getString("Food"),rs.getString("Quantity"),rs.getString("Price")
            };
            tblModel.addRow(row);
        }
        tblModel.fireTableDataChanged();
    } catch (SQLException ex) {
        Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
     private void loadData(){
        try{
            tblModel = new DefaultTableModel();
            tblModel.setColumnIdentifiers(new String[]{"ID","Room","Food","Quantity","Price"});
            jTable1.setModel(tblModel);
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e);
        }
    }
     
     private void detele(){
         String room = jTable1.getValueAt(jTable1.getSelectedRow(),1)+ "";
         try {
        String sql = "delete from orderfood where Room = ?"; 
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_manager","root","123");
        PreparedStatement statement = con.prepareCall(sql);
        statement.setString(1, room);
        statement.execute();
    } catch (SQLException ex) {
        Logger.getLogger(OrderFood.class.getName()).log(Level.SEVERE, null, ex);
    }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Adobe Arabic", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_order_history_70px_1.png"))); // NOI18N
        jLabel1.setText("Order Food");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 314, 415));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 99, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Exit\n");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 172, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String room1 = jTable1.getValueAt(jTable1.getSelectedRow(),1)+ "";
     String ID =jTable1.getValueAt(jTable1.getSelectedRow(),0)+ "";
     String food = jTable1.getValueAt(jTable1.getSelectedRow(),2)+ "";
     String quantity = jTable1.getValueAt(jTable1.getSelectedRow(),3)+ "";
     String price = jTable1.getValueAt(jTable1.getSelectedRow(),4)+ "";
            
            
        
        com.itextpdf.text.Document doc= new com.itextpdf.text.Document();
        try{
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_manager","root","123");
             String sql = "Select * from checkin where RoomNumber = `"+room1+"'";
             st = con.createStatement();
             rs = st.executeQuery(sql);
             if(rs.next()){
            PdfWriter.getInstance(doc, new FileOutputStream("F:\\Hotel\\OrderFood\\"+room1+".pdf"));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                                                               Food\n\n");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("****************************************************************************************************************");
            doc.add(paragraph2);
            Paragraph p4 = new Paragraph("Bill Order Food:\n"+"ID Bill: "+rs.getInt(1)+"\n"+"Room Number: "+rs.getString(13)+"\n");
            doc.add(p4);
            doc.add(paragraph2);
            Paragraph p5 = new Paragraph("Thank you for using our service");
            
            PdfPTable tbl = new PdfPTable(5);
            PdfPCell c1 = new PdfPCell(new Phrase("ID"));
            tbl.addCell(c1);
            PdfPCell c2 = new PdfPCell(new Phrase("Room"));
            tbl.addCell(c2);
            PdfPCell c3 = new PdfPCell(new Phrase("Food"));
            tbl.addCell(c3);
            PdfPCell c4 = new PdfPCell(new Phrase("Quantity"));
            tbl.addCell(c4);
            PdfPCell c5 = new PdfPCell(new Phrase("Price"));
            tbl.addCell(c5);
            
            tbl.addCell(ID);
            tbl.addCell(room1);
            tbl.addCell(food);
            tbl.addCell(quantity);
            tbl.addCell(price);
           doc.add(tbl);
           doc.add(paragraph2);
           doc.add(p5);
             }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        doc.close();
        detele();
        loadData();
            loaddata();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
